### ISSUE TITLE
Arlo Go V2

### ISSUE THREAD

**Issue by njaouen** [twrecked/pyaarlo#101]
Hi,
I am wondering if the current Arlo Go V2 would work with Pyaarlo, or if code updates would be required ?
Thanks.

**Comment by njaouen** [comment]
Except I guess for the introduction of :
MODEL_GO_2 = "VML2030"

**Comment by twrecked** [comment]
That's a good question. I think it might just work but if the camera has special features - ie, it's its own base station -  we might need to add the model number so we can check that and act on it.

You can see examples of tailoring for a particular device in `__init__.py` around line 685.

**Comment by twrecked** [comment]
merge pulled so I'm closing...
