### ISSUE TITLE
Device name with spaces

### ISSUE THREAD

**Issue by burner1024** [twrecked/pyaarlo#154]
Hi.
Is it possible to add a substitution for device names with spaces replaced by underscore or dash? `NN` or something.
Spaces are useful in web ui, but in filenames, not great.

**Comment by twrecked** [comment]
Filenames in what situation?

**Comment by twrecked** [comment]
I'll add an `NN` and run the name through `slugify` with underscores as the separator. 

I'm hoping to get a new version out today so I'll add this.

**Comment by twrecked** [comment]
Should be in the latest release.

**Comment by burner1024** [comment]
Cool, thank you!
