### ISSUE TITLE
Is save_media_to supposed to work continuously?

### ISSUE THREAD

**Issue by burner1024** [twrecked/pyaarlo#159]
When `save_media_to` is set, are the files supposed to be downloaded continuously as new records appear in the cloud? Right now it seems to be downloading the files up to the script's launch date, no updates after that.
From the readme, I can't quite figure out if that's a bug or correct behaviour.

My usage is just 
```python
    arlo = pyaarlo.PyArlo(
        username=USERNAME,
        password=PASSWORD,
        tfa_type=Config.config("tfa_type"),
        tfa_source=Config.config("tfa_source"),
        tfa_retries=Config.config("tfa_retries"),
        tfa_delay=Config.config("tfa_delay"),
        tfa_host=Config.config("tfa_host"),
        tfa_username=Config.config("tfa_username"),
        tfa_password=Config.config("tfa_password"),
        synchronous_mode=True,
        save_state=False,
        dump=dump,
        storage_dir="aarlo",
        verbose_debug=verbose_debug,
        backend="sse",
        save_media_to=PATH,
    )
```

**Comment by twrecked** [comment]
It should update new recordings. I'll double check it's still working here.

A couple of things to try:
- try without setting the `backend`, it might  not be using `sse`
- try with `no_media_upload = True`, it might be you're not being sent notifications that recordings have happened

**Comment by burner1024** [comment]
Thanks for clarification.
There was an issue before, but it seems to be downloading now. Maybe related to something else. I'll update if can narrow it down.
