### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Zaschii** [twrecked/pyaarlo#4]
Install command is wrong... should look like 

pip install git+https://github.com/twrecked/pyaarlo

Installation failed... syntax error...

  Running command git clone -q https://github.com/twrecked/pyaarlo /tmp/pip-req-build-365omybz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-365omybz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-365omybz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-365omybz/pip-egg-info
         cwd: /tmp/pip-req-build-365omybz/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-365omybz/setup.py", line 18
        author_email='steve.herrell@gmail.com',
                   ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mberry73** [comment]
Same here. Install failed.

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/twrecked/pyaarlo
  Cloning https://github.com/twrecked/pyaarlo to /tmp/pip-req-build-ifvjvbwc
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-ifvjvbwc/setup.py", line 18
        author_email='steve.herrell@gmail.com',
                   ^
    SyntaxError: invalid syntax
 
    ----------------------------------------

**Comment by twrecked** [comment]
Sorry about that I haven't ran the pip installation process in a while. Docs and install are fixed now.

**Comment by twrecked** [comment]
It's all fixed now so I'm closing this.
