### ISSUE TITLE
Set Brightness value of a camera

### ISSUE THREAD

**Issue by m0urs** [twrecked/pyaarlo#44]
I can check the current brightness value of a camera with

cam.brightness

but, can I also set the brightness value for a camera like

cam.brightness = 3

?

I tried that but it seems not to change the birghtness value of the camera.

**Comment by m0urs** [comment]
Ah sorry, I just saw that I made a mistake in my script. I will try again ....

**Comment by m0urs** [comment]
It does not seemt o work:

This shows me the correct camera, so "camera" should contain the correct information.

print("camera: name={},device_id={},state={}".format(camera.name, camera.device_id, camera.state))

This shows the correct brightness value:

print(camera.brightness)

However this statment fails:

camera.brightness = 2

with error:

AttributeError: can't set attribute

**Comment by twrecked** [comment]
Setting the brightness isn't supported. It should be easy enough to add.

**Comment by twrecked** [comment]
Should be fixed by PR #48 

Valid values are -2, -1, 0, 1 and 2.

**Comment by m0urs** [comment]
Thank you very much. This works fine!
