### ISSUE TITLE
Crash: "File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 222, in _set_mode_v2_cb"

### ISSUE THREAD

**Issue by m0urs** [twrecked/pyaarlo#45]
Today I had that error in my python script which is using "pyaarlo" to change modes of my base stations:

Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]: Traceback (most recent call last):
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:   File "/opt/fhem/arlo-fhem/arlo-fhem.py", line 167, in <module>
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:     base.mode = 'armed'
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 238, in mode
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:     _set_mode_v2_cb(1)
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:   File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 222, in _set_mode_v2_cb
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]:     if body.get('success', False) is True or body.get('resource', '') == 'activeAutomations':
Oct 15 18:33:43 raspberrypi02 arlo-fhem[9673]: AttributeError: 'NoneType' object has no attribute 'get'

"base" is the base station object I want to modifiy with "base.mode = 'armed'"
At that time it seems that in File "/opt/fhem/arlo-fhem/pyaarlo/base.py", line 222, the "body" object is not defined.

Could this be because the connection to Arlo has been closed?

Independent of the reason: Do we need to to do some kind of error checking to make sure body does always have the correct content so that the script does not crash at that point?

Unfortunatley I am not a very skilled Python developer so I do not fully understand everything in the script :-(

**Comment by twrecked** [comment]
Do we know what build of pyaarlo this is? There were some base station modes fixes put in recently.

But also, I'll double check the code around the `v2` mode setting. I know Arlo changed something recently which was causing the mode requests to fail in new and exciting ways.

**Comment by m0urs** [comment]
> 
> 
> Do we know what build of pyaarlo this is? There were some base station modes fixes put in recently.
> 
> But also, I'll double check the code around the `v2` mode setting. I know Arlo changed something recently which was causing the mode requests to fail in new and exciting ways.

Yes, it should be your most current master version ...

**Comment by m0urs** [comment]
Should fix for https://github.com/twrecked/pyaarlo/issues/40 fix also this issue (as the error sound similar): AttributeError: 'NoneType' object has no attribute 'get'?

**Comment by twrecked** [comment]
I think Arlo changed something on their back end and it's finding some holes in my code.

What kind of camera is this?

**Comment by twrecked** [comment]
It was broke on mine too. It should be fixed by PR #47 

Arlo changed their response to a mode change and I had to handle the new case.

**Comment by m0urs** [comment]
After updating my code to your current master, I do see now my script hanging while setting the modes. I do have a base station and two Arlo bridges which I do set this way:

```
<...>
       elif command == 'set-mode':
            if parameter1 == 'deaktiviert':
                base = getDeviceFromName("Home",arlo.base_stations)
                base.mode = 'disarmed'
                base = getDeviceFromName("Bridge_AZMichael",arlo.base_stations)
                base.mode = 'disarmed'
                base = getDeviceFromName("Bridge_AZSabine",arlo.base_stations)
                base.mode = 'disarmed'
<...>
```

getDeviceFromName() does get th base station object based on the name like:

```
def getDeviceFromName(name, devices):
    for device in devices:
        if device.name == name:
            return(device)
    return("")
```

It seems that changing the modes for a base station does still work as before. However, setting the mode of the bridge does lead to a hanging script for 60 seconds. It does set the mode of the bridge correctly but then "sleeps" for 60 seconds. Afterwards I can send another command again.

I attach a debug.log where I t
[debug-encrypted.log](https://github.com/twrecked/pyaarlo/files/5423349/debug-encrypted.log)
riedto arm the Bridge_AZMichael.

Could you please have a look?  Let me know where I can help you ...

Thanks a lot!

**Comment by twrecked** [comment]
Can you add the following to `pyaarlo.PyArlo` and try again. It was missing some debug I need.

```python
                      dump=True, verbose_debug=True
```

**Comment by m0urs** [comment]
I wil do that as soon as Arlo (Cloudflare) has whitelisted my IP again ;-) It seems that experimenting with the python script is something Cloudflare does not like ... Had that a few days ago also.

I saw that with these debugging parameters, my account details (user, password etc.) will be written to the debug log. That is something I would not like. Anything I can do? 

I tried with "type ..\debug.log | python pyaarlo -u <username> -p <password> anonymize" but that does not work (2020-10-22 17:39:40,328:pyaarlo:ERROR: authentication failed)

Maybe it does not work as I am unable to login with these credentials?

**Comment by m0urs** [comment]
It seems that Cloudflare will block me as soon as I try to use the debug parameter you wrote above ... If I remove them again, I can login again. Seems to be strange, but I just tried it again on another machine with another IP as well ..

**Comment by twrecked** [comment]
The file is just plain text so you can delete the username/password from the file before passing them in pyaarlo. But I'll look at a way of blocking that debug or removing it from the anonymize.

**Comment by m0urs** [comment]
Thanks, I pulled the new version. However: I am still uanble to login if I add the two parameters. Maybe I did something wrong? This is the login line:

`arlo = pyaarlo.PyArlo(username=username, password=password,tfa_source='imap', tfa_type='email', tfa_host=tfa_host, tfa_username=tfa_username, tfa_password=tfa_password, synchronous_mode=True, refresh_devices_every=3, dump=True, verbose_debug=True)
`
If I use this line, it works:

`
arlo = pyaarlo.PyArlo(username=username, password=password,tfa_source='imap', tfa_type='email', tfa_host=tfa_host, tfa_username=tfa_username, tfa_password=tfa_password, synchronous_mode=True, refresh_devices_every=3)`

**Comment by twrecked** [comment]
My bad. Try without `dump=True`

**Comment by m0urs** [comment]
This time it worked ;-) However I needed to anonymize some more things like the URLs pointing to the last image, the thumbnails etc. Hopefully I did not delete anything valuable.

[debug-encrypted.log](https://github.com/twrecked/pyaarlo/files/5424541/debug-encrypted.log)

**Comment by twrecked** [comment]
Found it. I'll fix it. It looks like there are 2 different returns possible for the mode command. I need to handle both.

**Comment by twrecked** [comment]
Can you try the master again?

**Comment by m0urs** [comment]
Thank you! This seems to work again now.

If there is a mode to change and the mode has been changed, a short time later something like this is printed out (for every device where the mode has been changed):

`<RequestsCookieJar[Cookie(version=0, name='__cfduid', value= ........ comment=None, comment_url=None, rest={}, rfc2109=False)]>
`
Any idea where this is coming from? Can I suppress that somehow?

**Comment by twrecked** [comment]
Where there anything else on that line?

**Comment by m0urs** [comment]
I shortened the line, means I delete the part represented by "........". Start and end was exactly what you see above. I did not see anything else.

My debug code at the beginning of my script is:

```
# set up logging, change ERROR or INFO to DEBUG for a *lot* more information
logging.basicConfig(level=logging.ERROR,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    filename='debug.log')
_LOGGER = logging.getLogger('arlo-fhem')

```

**Comment by twrecked** [comment]
How long after? I'm waiting 90 seconds and not seeing anything here.

**Comment by m0urs** [comment]
Only a few seconds.

**Comment by m0urs** [comment]
I created a minimal sample file with which I can reproduce the output I mentioned. And I saw that there are errors reported as well, although setting the mode is successful. Be ware: The mentioned output does only appear if the mode is changed. So in my example, if the base station is already disarmed, the output does not happen. And: If you leave out the sleep command, the output is also NOT written.

Here is my sample script:

```
#!/usr/bin/python3

import pyaarlo
import time

USERNAME = "user"
PASSWORD = "password"

##### Start Test Code ####

arlo = pyaarlo.PyArlo(username=USERNAME, password=PASSWORD, synchronous_mode=True)
base = arlo.base_stations[0]
base.mode = 'disarmed'
time.sleep(5)
arlo.stop()

```

This is the output generated:

```
attempt 1: error in response when setting mode=
{'59G1865E007ED': {'activeModes': ['mode0'],   
                   'activeSchedules': [],      
                   'timestamp': 1603532082481},
 'resource': 'activeAutomations'}
attempt 2: error in response when setting mode=
{'59G1865E007ED': {'activeModes': ['mode0'],   
                   'activeSchedules': [],      
                   'timestamp': 1603532082768},
 'resource': 'activeAutomations'}
attempt 3: error in response when setting mode=
{'59G1865E007ED': {'activeModes': ['mode0'],
                   'activeSchedules': [],
                   'timestamp': 1603532083002},
 'resource': 'activeAutomations'}
Failed to set mode.
<RequestsCookieJar[Cookie(version=0, name='__cfduid', .......................................... , domain='ocapi-app.arlo.com', domain_specified=False, domain_initial_dot=False, path='/', path_specified=True, secure=False, expires=1603532111, discard=False, comment=None, comment_url=None, rest={}, rfc2109=False)]>
file not written
```

**Comment by m0urs** [comment]
Besides the strange output the original crash nas no longer happened with the new version. So your fix seems to work!
