### ISSUE TITLE
Schedule multiple snapshots without blocking

### ISSUE THREAD

**Issue by diffuse** [twrecked/pyaarlo#49]
Thanks for writing this excellent library.  I've been attempting to make all cameras connected to a base station simultaneously take snapshots.  I accomplished this by calling `get_snapshot` in a separate thread on each `ArloCamera` object within `arlo.cameras`.  I see that it appears to be a race if multiple threads call the `get_snapshot` method on the same `ArloCamera` object, but from what I can tell, one thread per `ArloCamera` object seems to work fine.  I followed each  call within `get_snapshot`, and it looks like you protect every call that alters state with a `threading.Lock`, but I was hoping you could help me with the following questions:

1.  Are my findings correct/is it safe to concurrently call `get_snapshot` on multiple camera objects, as long as there is only one thread per camera?
2.  Is there a better way to asynchronously schedule snapshots, then use callbacks to download them when ready?
3.  Are base stations also thread-safe, or does this only work for one base station at time?

If it helps, here is more or less what I've been using to do this (running successfully for about an hour with multiple snapshots per minute):

```python
def get_and_use_snapshot(camera):
    # get snapshot
    img_bytes = camera.get_snapshot(timeout=10)
    img = Image.open(io.BytesIO(img_bytes))

    # use snapshot

def capture_mt(arlo):
    threads = [threading.Thread(target=get_and_use_snapshot, args=(camera,)) for camera in arlo.cameras]

    for t in threads:
        t.start()

    for t in threads:
        t.join()
```

**Comment by twrecked** [comment]
1. Yes, your findings are correct. You can actually call `get_snapshot` from multiple threads on the same camera object. Only the first one will do the work, the rest will just wait for it to finish.

2. Definitely. Look at `example/monitor_all` for handling callbacks. If you call `request_snapshot` you will (should) receive 2 callbacks:
   - `LAST_IMAGE_SRC_KEY - lastImageSource` starting with `snapshot/`
   - `LAST_IMAGE_DATA_KEY - presignedLastImageData` containing the image data.

3. They should be. Although - being honest - it's only been tested within the Home Assistant environment.

**Comment by diffuse** [comment]
Awesome, thank you for the extremely quick answers!  I have plans to at some point acquire multiple base stations and try this.  If/when I do, I can let you know how it behaves.

**Comment by twrecked** [comment]
It won't make much of a difference to your code. `arlo.cameras` will still contain all your cameras and `arlo.base_stations` will have 2 or more entries. It's safe the snapshot across different base stations at the same time.

**Comment by diffuse** [comment]
Confirmed working with:

```python
def snapshot_callback(camera, attr, value):
    # convert snapshot to PIL Image
    print(f'got snapshot from {camera.name}')
    img = Image.open(io.BytesIO(value))

    # use snapshot

# register snapshot callback with each camera
for camera in arlo.cameras:
    camera.add_attr_callback(pyaarlo.constant.LAST_IMAGE_DATA_KEY, snapshot_callback)

# request some snapshots
for camera in arlo.cameras:
    camera.request_snapshot()
```

Thanks again for the help!
