### ISSUE TITLE
detecting network disconnect -- what is the proper way?

### ISSUE THREAD

**Issue by shissam** [twrecked/pyaarlo#65]
I may be misunderstanding how to detect a disconnect with the servers in a long running session I would get (I did a home network reset)

2021-06-07 15:58:14,853 - pyaarlo - WARNING - error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2021-06-07 15:58:17,002 - pyaarlo - WARNING - error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}

I'd like to detect that and assumed that "is_connected" was the way to go, but that appears to be an incorrect assumption.

is_connected() still returns 'True" after this occurs. what is the proper way to (periodically) check the health of the connection with the server?

consider the following code:

arlo = pyaarlo.PyArlo( username=USERNAME,password=PASSWORD,
                    tfa_source='imap',tfa_type='email',
                    tfa_host='imap.gmail.com',
                    tfa_username=XXXXXXXXX,
                    tfa_password=ZZZZZZZZZZ,
                    storage_dir='aarlo',
                    refresh_devices_every=3 )

…
after successful login
….

print('starting with mode=' + arlo.base_stations[0].mode[:80], flush=True)

# hang around for 1 day and relogin (by exiting)
# unless something goes bad during the day
#
print('waiting 1 day', flush=True)

#time.sleep(86400)

for x in range(1, 86400, 30):
  try:
    if arlo.is_connected:
      print ("all OK; waiting another 30 seconds")
      pass

    if not arlo.is_connected:
      print ("all NG: we lost connection to arlo", flush=True)
      break

    time.sleep(30)

  except:
    print("somethings wrong, NG", flush=True)
    break

arlo.stop()
print('done - exiting')
sys.exit(0)

**Comment by twrecked** [comment]
The "Device Offline" message is coming back from the Arlo server so, technically, we are still connected. (It's complicated behind the scenes, we talk to Arlo and the devices talk to Arlo but we can't talk directly to each other.)

If you are looking to see if individual base stations or devices are there you need the `is_unavailable` property. Something like:

```python
if arlo.base_stations[0].is_unavailable:
  print("base station 0 has gone!")
```

It reflects the `connectedState` key passed back from Arlo.

Let me know if that works.

**Comment by shissam** [comment]
i've adopted your suggested code to my app, I am striving to reproduce the state which initiated my question here. My machine is wired to the network, so i disconnected it for 45 min - expecting to get either "not connected" or "is_unavailable" state which did not occur. after reconnecting the machine - pyaarlo simply continued where I left it before the disconnect nothing was wrong (which is great!).

so i am not done testing, tomorrow i will be doing another router firmware update (this is what I did earlier to get the 'error in response')

i promise to report back when I know more. But I'd bet your solution is what i am looking for.

thx!

**Comment by twrecked** [comment]
I've been thinking about this some more and I should have checked my code.

`is_connected` will be False if `pyaarlo` disconnects and can't connect back. I think your issue might be it can't tell it has been disconnected. Try adding `stream_timeout=120` to your `PyArlo` parameters.

**Comment by shissam** [comment]
okay - did the router firmware upgrade and the pyaarlo app failed as expected, the base station was unavailable and I was able to detect that in code and successfully restart once the network was healthy again.

so in my opinion and experience here, i now know better how to handle error conditions.

here is what my log shows:

`arlo is connected`
`base station is available`
`waiting 1 day`
`2021-06-09 14:32:02,760 - pyaarlo - WARNING - request-error=ReadTimeout`
`2021-06-09 14:32:02,790 - pyaarlo - WARNING - request-error=ConnectionError`
`all NG: base station is unavailable`
`2021-06-09 14:32:06,429 - pyaarlo - WARNING - request-error=ConnectionError`
`done - exiting`

FWIW: for this round I DID NOT use `stream_timeout=120`, i simply integrated `arlo.base_stations[0].is_unavailable` tests in my idle, noop, loop

I am closing this, unless you want to reopen and, if needed, I can run more/different tests for you. -- just let me know.
