### ISSUE TITLE
2FA not parsing mail properly?

### ISSUE THREAD

**Issue by Jopand** [twrecked/pyaarlo#96]
When running 2FA, I get the following errors:
[pyaarlo] imap message read failed'int' object has no attribute 'decode'
[pyaarlo] 2fa core retrieval failed
[custom_components.aarlo] unable to connect to Arlo: attempt=1,sleep=15,error=2fa core retrieval failed

I added some printouts to debug a bit. Seems like this line is causing the issue:
https://github.com/twrecked/pyaarlo/blob/2d6941dc903fe2fca01ac9d82fe708d1299ebe81/pyaarlo/tfa.py#L113

I have to change "[0][1]" to  "[1][1]", then it seems to work

**Comment by qosmio** [comment]
I was having the same issue, however this didn't work for me. The correct format should always have a tuple that has a length of with the body in the first tuple at ```msg[0][1]```.

I haven't looked much into why it's returning a tuple with 3 items. It doesn't seem to be the correct email either, it seems to be for a "confirm your email". Could you confirm?

You can add a check to ensure the message is in bytes before processing. 
```python
"""check if msg is bytes, then process email"""
if isinstance(msg[0][1], bytes):
    for part in email.message_from_bytes(msg[0][1]).walk():
        if part.get_content_type() == "text/html":
            for line in part.get_payload(decode=True).splitlines():
...
```

**Comment by Jopand** [comment]
I haven't digged much more into it, but my change has worked ever since. I'm using a yahoo mail, but not sure if that makes a difference

**Comment by Jopand** [comment]
FYI, the mails I'm getting are titled "Your one-time authentication code from Arlo", so it's definitely the correct email it is parsing

**Comment by stelle11** [comment]
I had same problem (also using yahoo) and tried first by changing the index number from 0 to 1 as you suggested Jopand but that didn't solve it.
I then added the if statement you suggested qosmio and that actually solved it for me :)

**Comment by jkrcknbrg** [comment]
I'm having the same problem, also using Yahoo email.

With the 'if' statement, I was unsuccessful with this error:
`2022-06-19 07:29:48,177 - pyaarlo - ERROR - 2fa core retrieval failed`

Changing the index from "[0][1]" to "[1][1]" failed with this error:
`2022-06-19 07:33:35,839 - pyaarlo - ERROR - unable to read mode, try forcing v2`

My only workaround has been entering the TFA code in the console.

**Comment by gtawelt** [comment]
Try this for yahoo Mail
`                    res, msg = self._imap.fetch(msg_id, "(BODY[TEXT])")
                    if isinstance(msg[0][1], bytes):
                        for part in email.message_from_bytes(msg[0][1]).walk():
                            if part.get_content_type() == "text/plain":
                                for line in part.get_payload(decode=True).splitlines():`

**Comment by qosmio** [comment]
@Jopand I believe it’s definitely related to Yahoo’s YMail as well. That’s what I’ve been using too.

@stelle11 I’m glad to here! Hopefully if this works for more people using Yahoo I can create a pull request.

@jkrcknbrg I know you’ve switched over to using a different email, but if you were to try again, I found that disabling the integration for 5 minutes, and deleting all email sent from Arlo should give you a clean slate of no expired tokens.

**Comment by Jopand** [comment]
@qosmio I'll try out the fix tomorrow and see if it works for me as well

**Comment by Jopand** [comment]
The fix seems to work here as well 👍

**Comment by Jopand** [comment]
I made a printout of msg[0][1] and msg[0][1]..

msg[0][1]: 50

... nothing else...

msg[1][1]:
b'Received: from 127.0.0.1\r\n by atlas-production.v2-mail-prod1-gq1.omega.yahoo.com pod-id atlas--production-gq1-6db95f6ddc-xz57w.gq1.yahoo.com with HTTP..... + a lot more. LOOOOOONG string containing the entire mail

**Comment by imopen** [comment]
same issue for me, using Yahoo, i solved using:

`                    if isinstance(msg[1][1], bytes):
                        for part in email.message_from_bytes(msg[1][1]).walk():
`

**Comment by Jopand** [comment]
Will this ever be fixed? Multiple users using Yahoo have this tfa issue. The solution is above. Why not take it in and make it work with Yahoo as well as other tfa sources?

Since hass-aarlo has excluded the code of this project and rely entirely on the package, we can no longer manually fix the code after each update. So it is now definitively broken until something is done.

**Comment by twrecked** [comment]
Sorry, I'll try and take a look later. I've just managed to find time to look at this stuff again.

**Comment by twrecked** [comment]
I pushed a fix (and updated the alpha hass-aarlo release). Let me know if it works.

I dug out an old yahoo account I had and the change works with that and gmail.

**Comment by Jopand** [comment]
It seems to work for me as well... Nice job 👌
